### ISSUE TITLE
Question about Test in CI

### ISSUE THREAD

**Issue by RuizuKun-Dev** [BusyCityGuy/finite-state-machine-luau#11]
Hello, I noticed that this repository is using JestLua and Lune for testing, and I was wondering what kind of test is it? does it test code that runs in Roblox? would this be a substitute for using Run In Roblox?

I'm interested in using TDD and Testing in my CI but I have no idea where to start, I don't understand Github Actions/Workflow and Run In Roblox seems to be having a lot of issues

**Comment by BusyCityGuy** [comment]
Lune is a standalone runtime for Luau, so yes indeed, it is the alternative I have chosen to running tests with run-in-roblox.

The tests are written in jest which was originally a javascript library, but Roblox ported it over to Luau and made it source available. The nice folks over at jsdotlua have created a fork that is usable without Roblox's internal dependencies, which is the fork I am using in this project.

These tests are well-suited for projects that have code that is:
- Modular: Easy to require the part you want to test from within your testing code
- Pure: Given the same input, your code always returns the same output. That is, it doesn't depend on external factors like game state, networking conditions, or other unknown variables

As an example, this state machine project is very limited in scope, it's _just_ code with no dependency on Roblox's data object model. This makes it easy to know all the edge cases that need to be tested and be able to test them without needing to run in Roblox Studio.

I recommend reading up on [how to set up github actions workflows](https://docs.github.com/en/actions/using-workflows/about-workflows). In my case, I have just one script for continuous integration, found here: https://github.com/BusyCityGuy/finite-state-machine-luau/blob/main/.github/workflows/ci.yml

I'll eventually add a continuous deployment script to deploy this project to various consumers like a release download, wally, maybe the Roblox marketplace, etc.

You can read the script to see how it works. It runs on pull requests & main to do a few things:
- Lint with Selene
- Check format with StyLua
- Analyze with luau-lsp
- Run jest tests with Lune

To get access to these tools within the github action runner, they need to be installed first. It's basically a blank linux machine, so it needs to go through the same setup you would need to if you were setting up the project by following [the Contribution readme](https://github.com/BusyCityGuy/finite-state-machine-luau/blob/main/CONTRIBUTING.md). So, the first step it does is deal with all the setup like installing Lune, Wally, and Aftman. It caches these tools to use in the rest of the jobs, where you'll notice each of the other jobs depends on the install-tools step and they first restore the installed items from the cache. You could avoid caching by doing it all in one job, but I wanted to break it out into separate jobs to stay organized.

Each of the jobs (lint, format, analyze, test) just runs the cli tool like you would on your machine. These cli tools are called from [Lune scripts](https://github.com/BusyCityGuy/finite-state-machine-luau/tree/main/lune), which are called from [shell scripts](https://github.com/BusyCityGuy/finite-state-machine-luau/tree/main/scripts) that define the parameters to give those Lune job scripts. 

The reason the tools are called from Lune scripts which are called from Shell scripts instead of calling the tools directly inside the workflow file is to make my life easier running these steps locally, ensuring local ci and github action ci is identical. To run the same ci steps locally, I added another `lune` script called `ci` which runs each of the same shell scripts that the github actions workflow runs, so I can test ci locally by just calling `lune run ci`. I also added another handy lune script, `lune run formatFix` to make all the formatting compliant with what gets checked in the `lune run formatCheck` script.

Hopefully this gives good enough of an overview to get you started on understanding the flow of things as you look at the source code. I recommend reading that [CONTRIBUTING.md](https://github.com/BusyCityGuy/finite-state-machine-luau/blob/main/CONTRIBUTING.md) file for more condensed information about how to use the development tools I've set up here.

**Comment by RuizuKun-Dev** [comment]
Thank you for the explanation! I appreciate you taking the time to write an elaborate and well thought out answer to my question 🙏🏻
